### ISSUE TITLE
GIF Support?

### ISSUE THREAD

**Issue by HDVinnie** [coderello/laravel-proximage#14]
Doing something like:

```
<span class="badge-user text-bold" style="background-image:url({{ proximage("https://i.imgur.com/F0UCb7A.gif")->get() }});">TEST</span>
```

The image gets proxied but is no longer animated.

https://images.weserv.nl/?url=ssl%3Ai.imgur.com%2FF0UCb7A.gif

**Comment by hivokas** [comment]
Unfortunately, this is a limitation of `images.weserv.nl`.

**Comment by HDVinnie** [comment]
Ok. Thanks for the heads up.
