### ISSUE TITLE
HTTPS origins should be prefixed with ssl:

### ISSUE THREAD

**Issue by TNovalis** [coderello/laravel-proximage#8]
For some image origins that require TLS we need `ssl:` prefixed before the image.

In the weserv docs they have this:
`HTTPS origin hosts can be used by prefixing the hostname with ssl:`

**Example**
`https://images.weserv.nl/?url=ssl:www.google.com/logos/logo.gif`

**Comment by hivokas** [comment]
If you have time and desire, you can send pull request with fix by yourself.
If not, then I'll do it myself soon.
